### ISSUE TITLE
Malcolm Dashboards not available

### ISSUE THREAD

**Issue by blvrkr** [idaholab/Malcolm#514] opened 2024-07-16 21:12 UTC
**Describe the bug**
Malcolm Dashboards are not loading. When navigating from Malcolm - Landing Page, add data wizard shows up.

**To Reproduce**
1. Install Malcolm from ISO (Virtual Machine Single Partition Quick Install)
2. Start Malcolm
3. Navigate to Malcolm - Landing page and from there to Malcolm Dashboards

**Expected behavior**
Malcolm Kibana dashboards available

**Screenshots and/or Logs**
![image](https://github.com/user-attachments/assets/c8d38495-c76c-441f-a2af-83a7d96a02fc)
Log exempt from terminal window which opens after launching "Start Malcolm":
```
dashboards-helper-1   | 2024-07-16T22:28:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (4m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:30:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (6m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:30:00Z  /data/index-refresh.py --index MALCOLM_OTHER_INDEX_PATTERN --template malcolm_beats_template --unassigned: failure (could not find Index ID for malcolm_beats_*)
dashboards-helper-1   | 2024-07-16T22:32:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (8m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:34:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (10m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:36:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (12m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:38:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (14m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:40:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (16m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:42:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (18m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:44:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (20m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:46:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (22m0s elapsed)
dashboards-helper-1   | 2024-07-16T22:48:00Z  /data/shared-object-creation.sh: not starting: job is still running since 2024-07-16 22:24:00 +0000 UTC (24m0s elapsed)
```
 (new message like above appears every 2 min)

**Malcolm Version:**
 - Version [e.g. v24.06.0]

**How are you running Malcolm?**
- [X] [ISO installed](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (on VM or dedicated hardware)
- [ ] via [Docker](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) on [Linux](https://idaholab.github.io/Malcolm/docs/host-config-linux.html#HostSystemConfigLinux)
- [ ] via Docker on [Microsoft Windows](https://idaholab.github.io/Malcolm/docs/host-config-windows.html#HostSystemConfigWindows)
- [ ] via Docker on [macOS](https://idaholab.github.io/Malcolm/docs/host-config-macos.html#HostSystemConfigMac)
- [ ] via [Kubernetes](https://idaholab.github.io/Malcolm/docs/kubernetes.html#Kubernetes) (please provide platform details: e.g., on-prem K3s, Amazon AWS EKS, Microsoft Azure AKS, etc.)
- [ ] other (please describe)

**Additional context**
- None

**Comment by mmguero** [comment] 2024-07-17 21:04
Either one of the other processes that the dashboards-helper container is depending on must not be starting correctly, *or* it's this issue #499.

If you run `./scripts/status` are there any containers that are listed as exited? If not, can you go to that bug I referenced and try running those two commands in the first comment and see if you get a similar result as illustrated in that output?

**Comment by blvrkr** [comment] 2024-07-18 08:07
All containers are up but I figured out that 'opensearch' is not being resolved correctly, as in https://github.com/idaholab/Malcolm/issues/499.

**Comment by mmguero** [comment] 2024-07-18 13:00
Okay, yeah, it felt like that's what was going on to me. I am still a bit stymied as to why this particular container has this issue, when it should be resolved internally like all of the other containers do and shouldn't rely on any DNS settings external to docker. The only thing I can say about it for now is to check the hosts DNS settings (even if it's not network-connected, make sure it's not set to something that can be reached; or removing DNS completely if it's actually not a network-connected device) and try again. I'll try to dig in and figure out the cause of this over the next week or so.

**Comment by mmguero** [comment] 2024-07-18 13:00
closing as duplicate of #499

**Closed as not planned by mmguero** 2024-07-18 13:00 UTC
Labels: bug
